### ISSUE TITLE
Problems saving the .esdl file to the drive

### ISSUE THREAD

**Issue by garciamsu** [ESDLMapEditorESSIM/docker-toolsuite#7]
Hello, I am having problems saving my esdl file to the drive.

Menu / File / Save to ESDL Drive

![Screenshot from 2022-10-07 21-21-21](https://user-images.githubusercontent.com/38272114/194680944-2ef19c87-ae90-4530-968d-d109c0d1be0e.png)

**Comment by edwinmatthijssen** [comment]
It looks like you’re trying to save to the EDR (Energy Data Repository), which is a read only part of the ESDL drive. 

In order to get folders in the Drive for projects you need to create groups in keycloak and assign users to it. Only those users will be able to read/write from/to those project folders on the ESDL drive. 

Please let me know if you manage to do this with these ‘limited’ instructions. Otherwise I will try to find some time to write some proper documentation for it.

**Comment by garciamsu** [comment]
Hi Edwin, thanks for your help. I was able to save the project in both the project and users folders, but what is the difference between saving in each one ???

**Comment by garciamsu** [comment]
Another query, why when I try to load the EDR information I get this error, if I'm just reading ????

![Screenshot from 2022-10-08 20-47-06](https://user-images.githubusercontent.com/38272114/194732493-af2fa543-26cf-4b81-932f-a9cb68d83c47.png)

**Comment by edwinmatthijssen** [comment]
The system is meant to be installed on a server and used by multiple people at the same time. People can work together in projects. Only members of a project will see the contents of the project. The user directory can be used for personal storage, only you can see that.

W.r.t. the 500 error, I’m not sure…. It also depends on your configuration files.  Probably you can find more information in the ESDL drive container.    But we still need to implement the private EDR functionality, such that people, organizations and projects can have their private data stored for reuse. So it could be possible that this is the expected behavior for the time being. 

My question would be, what do you want to do there, or are you just exploring all options and wandering around in the UI of the tool?

**Comment by garciamsu** [comment]
Hi Edwin, thank you very much for your answers.

I am exploring the graphical interface to understand its operation and possible applications in my research project
